version: "3"
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - client:/usr/src/backend-app/client
      - /usr/src/backend-app/client/node_modules
      - /usr/src/backend-app/client/build

  server:
    build: ./server
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/src/backend-app
      - /usr/src/backend-app/node_modules
      - client:/usr/src/backend-app/client
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
volumes:
  client: {}